### ISSUE TITLE
Compatibility with `Liquid`

### ISSUE THREAD

**Issue by kerrick-lyft** [pwwang/liquidpy#21]
I'm trying this example [from the official Liquid docs](https://shopify.github.io/liquid/filters/split/):

```
{% assign beatles = "John, Paul, George, Ringo" | split: ", " %}

{% for member in beatles %}
  {{ member }}
{% endfor %}
```

This gives me a `LiquidRenderError: [SyntaxError]`. Here is a full repro:

```
In [1]: from liquid import Liquid                                                                                                                     

In [2]: template = Liquid(''' 
   ...: {% assign beatles = "John, Paul, George, Ringo" | split: ", " %} 
   ...:  
   ...: {% for member in beatles %} 
   ...:   {{ member }} 
   ...: {% endfor %} 
   ...: ''', liquid_loglevel='debug')                                                                                                                 

In [3]: template.render()                                                                                                                             
---------------------------------------------------------------------------
LiquidRenderError                         Traceback (most recent call last)
<ipython-input-3-85d9502bc949> in <module>
----> 1 template.render()

/usr/local/lib/python3.7/site-packages/liquid/__init__.py in render(self, **context)
    227             LOGGER.debug("The compiled code:\n%s", strcode)
    228         except BaseException as exc: # pylint: disable=broad-except
--> 229             _render_failed(exc, finalcode, final_context)
    230         return ret

/usr/local/lib/python3.7/site-packages/liquid/__init__.py in _render_failed(exc, finalcode, final_context)
    112             msg.append(f'  {key}: {_shorten(str(val), 80)}')
    113 
--> 114     raise LiquidRenderError('\n'.join(msg)) from None
    115 
    116 class Liquid:

LiquidRenderError: [SyntaxError] invalid syntax (<LIQUID_COMPILED_SOURCE>, line 65)

Compiled source (elevate loglevel to hide this)
--------------------------------------------------
  60.       return obj[dot]
  61. 
  62.   # ENDED TAGGED CODE
  63. 
  64.   _liquid_ret_append('\n')
> 65.   beatles = ("John, Paul, George, Ringo" | split: ", ")
  66.   _liquid_ret_extend([
  67.     '\n',
  68.     '\n',
  69.   ])
  70.   for forloop, member in _Liquid_forloop_class((beatles)):

Context:
--------------------------------------------------
  true: True
  false: False
  nil: None
```

**Comment by pwwang** [comment]
Since `v0.5.0`, we have to backtick quote if we are using `liquidpy` expressions in `assign` node. The other thing is that, `python` doesn't have a function named `split`, we have to use an attribute filter:

```python console
In [1]: Liquid('''{% assign beatles = `"John, Paul, George, Ringo" | .split: ", "` %}
   ...: {{-beatles}}''').render()
Out[1]: "['John', 'Paul', 'George', 'Ringo']"
```

I will update the doc.

**Comment by pwwang** [comment]
By the way, `split` in the doc where you referred is actually a `liquid` filter. So alternatively, we can use `@split`.

**Comment by kerrick-lyft** [comment]
@pwwang I think this is still a bug. I still get a `LiquidRenderError` if I run this code:
```
from liquid import Liquid
template = Liquid('''
{% assign beatles = "John, Paul, George, Ringo" | split: ", " %}

{% for member in beatles %}
  {{ member }}
{% endfor %}
''')
template.render()
```
I don't really understand what you said about backticks and `@split`. The whole point of liquidpy is that it should be compatible with Liquid, right? So if there is an example from the official Liquid docs that doesn't work in liquidpy, that is a bug. It's not really helpful if liquidpy supports some other syntax that is similar to, but slightly different from, Liquid. There are already great templating libraries like Jinja for Python so if you want something that's similar to Liquid that works well with Python, you would just use Jinja unless you specifically needed Liquid compatibility.

**Comment by pwwang** [comment]
Well, we actually didn't expect that people are using the same template and switch languages that render it back and forth. 

However, it was designed to bring some (maybe as more as possible) features and grammar from `Liquid`, and maintain certain (of course we can't do 100%) compatibilities. When it's evolving, we found that we should also take more advantages from the language (Python) itself. That's why it became how it looks like now.

To revoke the compatibility with `Liquid`, we don't think it's necessary to redraw the functions that we have implemented. One option that I can think of is to add a configuration specifying the compatibility with `Liquid`. One could turn this on to acquire more compatibilities on the template rendering or turn this off the get more flexibilities which are given by `Python` itself.

I will reopen this and keep the discussion on util we make an agreement or project/milestone plan on this.

Thank you.

**Comment by pwwang** [comment]
@kerrick-lyft We have to keep current functionalities of `liquidpy` to make our other projects intact. After some discussion, we proposed to have a boolean configuration item `liquid_compatible` to indicate whether rendering the template in a `Liquid`-compatible or current way.

However, we have to set this indicator to `False` by default, because we have already had tons of templates written in a non-`Liquid`-compatible way. One can turn it on either in the `render` function or in the `config` node from the template.

What do you think?

**Comment by pwwang** [comment]
`0.6.0` is now compatible with the standard liquid template engine.
Feel free to re-open it if you have any related questions.
