### ISSUE TITLE
liquidpy is unsafe against malicious input

### ISSUE THREAD

**Issue by kerrick-lyft** [pwwang/liquidpy#22]
liquidpy is currently unsafe against malicious template inputs because it directly `exec`'s pieces of the input template in the Python interpreter. This means that anyone who can control or influence the content of the template can run arbitrary Python code (this is a [code injection attack](https://en.wikipedia.org/wiki/Code_injection)).

For example, rendering this template will remove all files on the system that the user has write access to:
```
{% assign foo = 1); import os; os.system('rm -rf /' %}
```

I think liquidpy should be re-written in a way such that it's not vulnerable to this sort of attack. To do this, you need to parse code in `assign` statements yourself, rather than generating Python code to do it. You should never be exec'ing anything string that came from the template (ideally you should never use exec at all).

In the meantime you should add a prominent message to the README (e.g. "liquidpy cannot safely be used with untrusted templates. Only use liquidpy in cases where you completely control the contents of the template string.") so that users don't open themselves up to a code injection attack.

**Comment by pwwang** [comment]
Thanks for bringing this up.

We had this discussion internally. We developed this for internal use at the very beginning of some other projects, so this wasn't put on agenda then. But, truly, we shall have put such statements in the documentation to remind people.

Actually, `assign` is not the only node that one could be code injection. Arbitrary codes can be put in many nodes, such as `from/import` (e.g. `import xxx; import os; os.system('...')`). An even eviler node is the `python` node, where one can execute any codes in it.

Since this is getting popular, we should definitely put this on the agenda. 

Here are the proposed action items:

- [ ] Put a safety section in the documentation
- [ ] List all nodes that are unsafe
- [ ] Add safety checker (`ast` parsing currently in my mind) for all those nodes
- [ ] Add a configuration (say `strict` to enable those checkers and disable `python` node)
- [ ] Give warnings when rendering a non-strict (`strict = False`) templates
- [ ] Raise exceptions when rendering strict templates if any safety checkers fail

Feel free to propose anything else that you think should be on the list as well.

**Comment by kerrick-lyft** [comment]
That makes sense, thanks!

**Comment by pwwang** [comment]
@kerrick-lyft 

I am writing some tests for the nodes to prove that they are truly unsafe. However, I found that `assign` is actually safe in the sample you gave:

```python
tpl = "{% assign foo = 1; import os; os.system('pwd') %}"
Liquid(tpl, liquid_loglevel='debug').render()
```

It actually gives a `LiquidRenderError`:
```python console
liquid.exceptions.LiquidRenderError: [SyntaxError] invalid syntax (<LIQUID_COMPILED_SOURCE>, line 15)

Compiled source (elevate loglevel to hide this)
--------------------------------------------------
  10.   true = _liquid_context['true']
  11.   false = _liquid_context['false']
  12.   nil = _liquid_context['nil']
  13.   _liquid_liquid_filters = _liquid_context['_liquid_liquid_filters']
> 14.   foo = (1; import os; os.system('pwd'))
  15. 
  16.   return ''.join(str(x) for x in _liquid_rendered)
```

Interestingly, the value was wrapped while being put into the python source, which unexpectedly prevents this kind of injection.

However, I did find nodes that are exploitable. For example:
```python
tpl = "{% import re; import os; os.system('touch somefile.txt') %}"
Liquid(tpl).render()
```
Template successfully rendered and `somefile.txt` created.

However, I am not sure where this injection is from. Since this is called `injection`, I am not assuming it comes from a template itself. It is more likely to be from the environments or the data that are passed in to render the template.

What I am saying is that we are actually not expanding the values of the data that are passing and compile them into python source. For example:

```python
Liquid("{% import lib %}").render(lib="re; import os; os.system('touch somefile.txt')")
```
will NOT be expanded into python source like this:
```python
import re; import os; os.system('touch somefile.txt')
```

So come back to the template itself. Then we are not detecting whether there is injection happening, but whether the template is benign. To this point, we can do a strict scanning for the nodes. Here, for instance, we should only allow one name right after `import`. Disabling `python` node is apparently another thing to do to make sure a template is benign. For example, one can do this in a template:
```liquid
{%python%}
def delete_world():
  import os
  os.system('rm -rf /')
{%endpython%}

{% assign foo = x or delete_world() %}
```
Here `liquidpy` is actually considering `x or delete_world()` is a valid expression to get a value for foo. At that checkpoint, we have no idea what `delete_world()` will be doing, unless we disable `python` node and disabling any other change to define such malicious code, for instance, in `import`: `{% import re; import os; delete_world = lambda os=os: os.system('rm -rf /')  %}`

I guess that will be enough to restrict a template to define arbitrary codes in the template.

Let me know your thoughts.
Thank you!

**Comment by kerrick-lyft** [comment]
@pwwang the example I posted should work. Note that there is no trailing parenthesis after `os.system('rm -rf /'`; in your repro you added a trailing parenthesis which caused a syntax error due to unbalanced parenthesis. Try this code:

```
from liquid import Liquid
tpl = "{% assign foo = 1); import os; os.system('pwd' %}"
Liquid(tpl, liquid_loglevel='debug').render()
```

To solve this, if you're going to take any code from the template and insert it into the generated Python code, you have to first pass it through `ast.literal_eval`. If it's something too complicated for `ast.literal_eval`, then you need to parse it yourself. It's not sufficient to have a set of checks to see if the code looks benign or not and then to pass it to `eval()`; there will always be some complicated case that you didn't think of.

You can do parsing using a hand-rolled parser or you can use a parser generator. I haven't done parsing in Python but https://wiki.python.org/moin/LanguageParsing has a list of different parser generator libraries that exist. I'm not sure if Liquid is complicated enough to require this approach vs just using a hand-rolled parser. You'd have to specify the grammar yourself (which isn't too hard) because it looks like there is no official one from Liquid https://github.com/Shopify/liquid/issues/1261

"Injection" here means injecting code from the template into the Python process. The template itself may be malicious, e.g. if you run a service that allows users to specify templated SQL queries (like Mode Analytics) or templated webpages (like Shopify).

**Comment by pwwang** [comment]
That makes sense for the "injection", which I think here, is basically letting the nodes do the things they are supposed to do (e.g. `assign` just assigns values to variables, instead of does something else (e.g. `import`)).

Using `ast.literal_eval` is not enough here to implement it since we meant to allow expressions in the `assign` node. And it has a compatibility issue with different python versions on evaluating expressions. For example, `ast.literal_eval("1+1")` gives `2` with python3.6, but an error with python3.7. We should be able to allow variables in such cases as well. So we might have to some ast parsing.

We will do some explorations on this.

**Comment by pwwang** [comment]
@kerrick-lyft After experimenting with `PLY` or `SLY` a little bit, we feel like that we can not afford to rewrite the whole lexical analyzer. So we are planning to do it for those unsafe nodes only. 

The other issue (maybe not an issue) for `PLY` or `SLY` is that they have to load the whole template string into memory and then start parsing. It is not an issue in terms of memory for a modern device, but just not friendly to streams and file-like objects.

Any comments?

**Comment by pwwang** [comment]
@kerrick-lyft 

We have now re-implemented the whole package using `lark-parser`, which makes `liquidpy` safe against malicious input, and also gives us chance to remove `exec`.

We are now a real "port" of shopify's liquid template language. We have grabbed tests from their code, as well as all functionalities listed in their documentation (https://shopify.github.io/liquid/), and supported most of their functionalities. This means the other issue (#21) you had should be solved by this branch.

Please check it at branch https://github.com/pwwang/liquidpy/tree/lark.

We haven't had a chance to detail the documentation at this stage. However, the usage is almost the same as the master one, but just with the configurations collapsed into one keyword argument `liquid_config`. Right now, only `debug` is supported for configuration (i.e. `Liquid('{{ "Hello world1" }}', liquid_config={'debug': True}).render(...)`. 

We are still on the way to push it to the master and publish it. But feel free to try and let us know if you have any questions.

**Comment by pwwang** [comment]
`liquidpy` is now remodeled with the full compatibility with the standard liquid template engine (`v0.6.0`). 
To implement that, we used a builtin lexer to identify the nodes and then lark-parser to parse each tag. In such a way, no malicious code is able to run is you are with the standard mode.

See docs for more details.

Closing this, but feel free to re-open if you have related questions.
